@startuml
'https://plantuml.com/sequence-diagram

title "US 5.1.2. Process View (Level 2)"

autonumber
participant "«component»:\nVisualization(UI)" as UI
participant "«component»:\nBackoffice" as BACK

[o-> UI: receives request to change user password
activate UI

UI -> BACK : requestPasswordAlteration(json)
activate BACK

BACK --> UI : answer
deactivate BACK

 <-- UI : answer
deactivate UI

[o-> UI: provides new password after clicking on the link
activate UI

UI -> BACK : updatePassword(json)
activate BACK

BACK --> UI : answer
deactivate BACK

 <-- UI : answer
deactivate UI
@enduml