@startuml

title "US 5.1.22. - Process View [Level 2]"

autonumber

participant "<<component>>\n Backoffice" as bo

[o-> bo: removeOperationType()
activate bo

<-- bo: success/insuccess
deactivate bo
@enduml