@startuml
title "US 5.1.1. Process View (Level 3) - Create User"

participant "<<Route>>\n StaffRoute" as ROUTE
participant "<<Controller>>\n StaffController" as CONTROL

participant "<<Service>>\n UserManager" as AUTHServ
participant "<<DTO>>\n UserDTO" as UserDTO
participant "<<Domain>>\n User" as USER
participant "<<Repository>>\n UserRepository" as AUTHRepo

participant "<<Service>>\n EmailService" as EMAILServ

participant "<<Service>>\n TokenManagementService" as TOKENServ
participant "<<component>>\n Token" as TOKEN
participant "<<DTO>>\n TokenDTO" as TOKENDTO
participant "<<Repository>>\n TokenRepo" as TOKENRepo

participant "<<Service>>\n StaffService" as STAFFServ
participant "<<Repository>>\n StaffRepository" as STAFFRepo
participant "<<Domain>>\n Staff" as STAFF


[o-> ROUTE : POST(userData)
Activate ROUTE

ROUTE -> CONTROL : createBackofficeUser(userData)
Activate CONTROL

CONTROL -> UserDTO** : toDTO(userData)
CONTROL -> AUTHServ : checkIfUserExists(userDTO)
Activate AUTHServ

AUTHServ -> AUTHRepo : existsById(userDTO.email)
Activate AUTHRepo

AUTHRepo --> AUTHServ : boolean
note right : checks if a user\n doesn't exist with\n that email
Deactivate AUTHRepo

AUTHServ --> CONTROL : boolean
Deactivate AUTHServ

CONTROL -> AUTHServ : createNewUser(userDTO)
Activate AUTHServ

AUTHServ -> USER**
AUTHServ -> AUTHRepo : save(user)
Activate AUTHRepo

AUTHRepo --> AUTHServ : user
Deactivate AUTHRepo

AUTHServ -> STAFFServ : findByEmail(userDTO.email)
activate STAFFServ
STAFFServ -> STAFFRepo : findByEmail(userDTO.email)
Activate STAFFRepo

STAFFRepo --> STAFFServ : staff
Deactivate STAFFRepo
STAFFServ --> AUTHServ : staff
deactivate STAFFServ
AUTHServ -> STAFFServ : associateUser(user, staff)
activate STAFFServ
STAFFServ -> STAFF : associateUser(user)
activate STAFF
STAFF --> STAFFServ : return
deactivate STAFF
STAFFServ -> STAFFRepo : save(staff)
Activate STAFFRepo
STAFFRepo --> STAFFServ : staff
Deactivate STAFFRepo
STAFFServ --> AUTHServ : return
deactivate STAFFServ

AUTHServ --> CONTROL : return
deactivate AUTHServ

CONTROL -> EMAILServ : sendSetupLink(userDTO)
Activate EMAILServ

EMAILServ -> TOKENServ : generateActivateAccountToken()
activate TOKENServ

TOKENServ -> TOKEN **

TOKENServ -> TOKENRepo : save(token)
activate TOKENRepo

TOKENRepo --> TOKENServ : return
deactivate TOKENRepo

TOKENServ -> TOKENDTO ** : toDTO(token)

TOKENServ --> EMAILServ : tokenDTO
deactivate TOKENServ

EMAILServ -> EMAILServ : sendEmail(emailString, tokenDTO, emailTitle, emailBody)
Activate EMAILServ

EMAILServ --> CONTROL : return
deactivate EMAILServ
deactivate EMAILServ

CONTROL --> ROUTE : return
deactivate CONTROL

Deactivate CONTROL
<-- ROUTE : success/error

Deactivate ROUTE
@enduml