@startuml
'https://plantuml.com/sequence-diagram

title "US 5.1.15. Process View (Level 3)"

autonumber

participant "<<component>>\n Routing" as ROUTE
participant "<<component>>\n XProfileListingController" as CONTROL

participant "<<component>>\n QueryParametersDTO" as QueryDTO

participant "<<component>>\n XService" as XServ
participant "<<component>>\n XRepository" as XRepo
participant "<<component>>\n XDTO" as XDTO

participant "<<component>>\n DynamicQueryGenerationService" as QUERYServ


[o-> ROUTE : GET()
activate ROUTE

ROUTE -> CONTROL : getAllXProfiles()
activate CONTROL

CONTROL -> XServ : getAllProfiles()
activate XServ

XServ -> XRepo : findAll()
activate XRepo

XRepo --> XServ : XprofilesList
deactivate XRepo

    loop for all the profiles in the list
        XServ -> XDTO ** : toDTO(Xprofile)

    end loop

XServ --> CONTROL : XprofileDTOList
deactivate XServ

CONTROL -> CONTROL : json(XprofileDTOList)

CONTROL --> ROUTE : json
deactivate CONTROL

[o<-- ROUTE : ok(json)
deactivate ROUTE

|||

[o-> ROUTE : POST(json)
activate ROUTE

ROUTE -> CONTROL : filterXProfiles(json)
note left
json contains the
query parameters
end note
activate CONTROL

CONTROL -> QueryDTO ** : toDTO(json)

CONTROL -> XServ : filterXProfiles(queryParametersDTO)
activate XServ

XServ -> QUERYServ : generateQueryText(queryParametersDTO)
activate QUERYServ

QUERYServ --> XServ : query
deactivate QUERYServ

XServ -> XRepo : findAllConditioned(query)
activate XRepo

XRepo --> XServ : XprofilesList
deactivate XRepo

    loop for all the profiles in the list
        XServ -> XDTO ** : toDTO(Xprofile)

    end loop

XServ --> CONTROL : filteredXProfilesDTOList
deactivate XServ

CONTROL -> CONTROL : json(XprofileDTOList)

CONTROL --> ROUTE : json
deactivate CONTROL

[o<-- ROUTE : ok(json)
deactivate ROUTE

|||

alt edit X profile

    [o-> ROUTE : PUT(json)
    activate ROUTE

    ROUTE -> CONTROL : updateXProfile(json)
    activate CONTROL

    CONTROL -> XDTO ** : toDto(json)

    ref over CONTROL

    **US 5.1.Y.**
    end ref

    CONTROL --> ROUTE : return
    deactivate CONTROL

else

    [o-> ROUTE : DELETE(json)

    ROUTE -> CONTROL : deleteXProfile(json)
    activate CONTROL

    CONTROL -> XDTO ** : toDto(json)

    ref over CONTROL

    **US 5.1.Z.**
    end ref

    CONTROL --> ROUTE : return
    deactivate CONTROL

end alt


alt success
[o<-- ROUTE : 200 OK

else failure

[o<-- ROUTE : 400 Bad Request
deactivate ROUTE
end alt


@enduml