@startuml
'https://plantuml.com/sequence-diagram

title "US 7.3.1 Process View (Level 1)"

autonumber

actor "BackOffice User" as BACK
participant "<<system (C4)>>\n Healthcare System" as SYS

BACK -> SYS : wants to distribute the operations by the rooms
activate SYS

SYS --> BACK : distributes the operations by the rooms
deactivate SYS

@enduml