@startuml

title "US 6.2.10 - Process View [Level 2]"

autonumber

actor Admin as ADM
participant "Visualization" as VIS <<Container C4>>
participant "MDBackoffice" as SYS <<Container C4>>

activate ADM
ADM -> VIS : create staff profile
activate VIS

VIS -> SYS : GetAllAvailable()
activate SYS

SYS --> VIS: specializations
deactivate SYS

VIS --> ADM: select specialization
deactivate VIS

ADM -> VIS: selects specialization
activate VIS

VIS -> SYS : CreateStaffProfile(json)
activate SYS

SYS --> VIS: success/insucess
deactivate SYS

VIS --> ADM : success/insucess
deactivate VIS
deactivate ADM

@enduml