@startuml

title "US 5.1.12. - Process View [Level 1]"

autonumber

actor Admin as ADM
participant "<<system (C4)>>\n Healthcare System" as SYS

activate ADM
ADM -> SYS : create staff profile
activate SYS

SYS --> ADM :  input staff data
deactivate SYS

ADM --> SYS : inputs staff data
activate SYS

SYS --> ADM : success/insucess
deactivate SYS
deactivate ADM

@enduml