image: mcr.microsoft.com/dotnet/sdk:8.0

pipelines:
  default:
    - parallel:
        - step:
            name: 'Build and Test'
            caches:
              - dotnetcore
            script:
              - echo "Starting build and tests..."
              - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}
              - dotnet restore
              - dotnet build --no-restore --configuration Release
              - dotnet test --no-build --configuration Release --test-adapter-path:. --logger:"junit;LogFilePath=$REPORTS_PATH/junit.xml"
            artifacts:
              - test-reports/**

        - step:
            name: 'Lint the Code'
            caches:
              - dotnetcore
            script:
              - export SOLUTION_NAME=sem5pi-24-25-dg38
              - export REPORTS_PATH=linter-reports
              - dotnet new tool-manifest
              - dotnet tool install JetBrains.ReSharper.GlobalTools
              - dotnet tool restore
              - dotnet jb inspectcode ${SOLUTION_NAME}.sln --output="${REPORTS_PATH}/jb-${BITBUCKET_BUILD_NUMBER}.xml"
            artifacts:
              - linter-reports/**