image: mcr.microsoft.com/dotnet/sdk:8.0

pipelines:
  default:
        - step:
            name: 'Build and Test'
            caches:
              - dotnetcore
            script:
              - echo "Starting build and tests..."
              - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}
              - dotnet restore
              - dotnet build --no-restore --configuration Release
              - dotnet test --no-build --configuration Release --test-adapter-path:. --logger:"junit;LogFilePath=$REPORTS_PATH/junit.xml"
            artifacts:
              - test-reports/**