@startuml
skinparam classAttributeIconSize 0
hide empty attributes
skinparam classBackgroundColor beige
skinparam ArrowColor #222222

class Name <<(V,#FF8B40)value object>> {}

class FirstName <<(V,#FF8B40)value object>> {}
class LastName <<(V,#FF8B40)value object>> {}
class FullName <<(V,#FF8B40)value object>> {}
class Phone <<(V,#FF8B40)value object>> {}
class Email <<(V,#FF8B40)value object>> {}
class Address <<(V,#FF8B40)value object>> {}
class Slot <<(V,#FF8B40)value object>> {}
class Date <<(V,#FF8B40)value object>> {}
class TimeInterval <<(V,#FF8B40)value object>> {}
class Function <<(V,#FF8B40)value object>>  {}
class Status <<(V,#FF8B40)value object>> {}

package "<<aggregate>> Patient" {
    entity Patient <<entity>> <<root>> {}
    class DateBirth <<(V,#FF8B40)value object>> {}
    class Gender <<(V,#FF8B40)value object>> {}
    class EmergencyContact <<(V,#FF8B40)value object>> {}
    class MRN <<(V,#FF8B40)value object>> <<identifier>> {}
    class AppointmentHistory <<(V,#FF8B40)value object>> {}
    class AppointmentHistoryStatus <<(V,#FF8B40)value object>> {}
    class AppointmentHistoryType <<(V,#FF8B40)value object>> {}
    class CreatedAt <<(V,#FF8B40)value object>> {}
}

package "<<aggregate MedicalRecord>>" {
    entity MedicalRecord <<entity>><<root>>{}
    class MedicalRecordDescription <<(V,#FF8B40)value object>> <<identifier>> {}
}

package "<<aggregate MedicalCondition>>" {
    entity MedicalCondition <<entity>><<root>>{}
    class MedicalConditionDesignation <<(V,#FF8B40)value object>>  {}
    class MedicalConditionCode <<(V,#FF8B40)value object>> <<identifier>> {}
    class MedicalConditionDescription <<(V,#FF8B40)value object>>  {}
}

package "<<aggregate Allergy>>" {
    entity Allergy <<entity>><<root>>{}
    class AllergyDesignation <<(V,#FF8B40)value object>> {}
    class AllergyCode <<(V,#FF8B40)value object>> <<identifier>> {}
    class AllergyDescription <<(V,#FF8B40)value object>>  {}
}

package "<<aggregate Staff>>" {
    entity Staff <<entity>><<root>>{}
    class LicenseNumber <<(V,#FF8B40)value object>> <<identifier>> {}
}

package "<<aggregate Doctor>>" {
    entity Doctor <<entity>><<root>>{}
}


package "<<aggregate OperationRequest>>"{
    entity OperationRequest <<entity>> <<root>> {}
    class OperationRequestId <<(V,#FF8B40)value object>> <<identifier>> {}
    class Priority <<(V,#FF8B40)value object>> {}
    class DateOfRequest <<(V,#FF8B40)value object>>  {}
    class DeadlineDate <<(V,#FF8B40)value object>>  {}
    class OperationRequestStatus <<(V,#FF8B40)value object>>
    class OperationRequestDescription <<(V,#FF8B40)value object>>

}

package "<<aggregate OperationType>>"{
    entity OperationType <<entity>> <<root>> {}
    class OperationTypeId <<(V,#FF8B40)value object>> <<identifier>> {}
    class RequiredStaff <<entity>>  {}
}

' Shared Value Objects with Operation Type Record
class EstimatedDuration <<(V,#FF8B40)value object>>  {}
class Phase <<(V,#FF8B40)value object>>  {}
class PhaseDuration <<(V,#FF8B40)value object>>  {}
class PhaseDescription <<(V,#FF8B40)value object>> {}
class OperationTypeStatus <<(V,#FF8B40)value object>> {}
class OperationTypeName <<(V,#FF8B40)value object>>  {}
class NumberStaff <<(V,#FF8B40)value object>>  {}



package "<<aggregate OperationTypeHistory>>"{
    entity OperationTypeRecord <<entity>> <<root>> {}
    class OperationTypeRecordId <<(V,#FF8B40)value object>> <<identifier>> {}
    class EffectiveDate <<(V,#FF8B40)value object>>  {}
    class OperationTypeRecordVersion <<(V,#FF8B40)value object>>  {}
    class RequiredStaffRecord <<(V,#FF8B40)value object>>   {}
}

package "<<aggregate Appointment>>"{
    entity Appointment <<entity>> <<root>> {}
    class AppointmentId <<(V,#FF8B40)value object>> <<identifier>> {}
    class AppointmentStatus <<(V,#FF8B40)value object>>  {}
}


package "<<aggregate Specialization>>"{
    entity Specialization <<entity>> <<root>> {}
    class SpecializationDenomination <<(V,#FF8B40)value object>> {}
    class SpecializationCode <<(V,#FF8B40)value object>> <<identifier>> {}
    class SpecializationDescription <<(V,#FF8B40)value object>>  {}
}

package "<<aggregate Room>>"{
    entity Room <<entity>> <<root>> {}
    class RoomNumber <<(V,#FF8B40)value object>> <<identifier>> {}
    class Capacity <<(V,#FF8B40)value object>>  {}
    class CurrentStatus <<(V,#FF8B40)value object>>  {}
    class AvailableEquipment <<(V,#FF8B40)value object>>  {}
}

package "<<aggregate RoomType>>" {
    entity RoomType <<entity>> <<root>> {}
    class RoomTypeCode <<(V,#FF8B40)value object>> <<identifier>> {}
    class RoomTypeDesignation <<(V,#FF8B40)value object>>  {}
    class RoomTypeDescription <<(V,#FF8B40)value object>>  {}
}

package "<<aggregate>> User" {
    entity User <<entity>> <<root>>
    class Username <<(V,#FF8B40) value object>> <<identifier>>
    class Role <<(V,#FF8B40) value object>>
}

package "<<aggregate>> Log" {
    entity Log <<entity>> <<root>>
    class Change <<(V,#FF8B40) value object>>
}

Log ---> "1" Date
Log ---> "1" Change
Log ---> "1" User

User -> "1" Status
User --> Username
User ----> Email
User --> Role

Doctor -> "1" Staff

Name --> FirstName
Name -> LastName
Name --> FullName

Room --> "1" RoomNumber
Room --> "1" RoomType
Room --> "1" Capacity
Room --> "1" CurrentStatus
Room --> "1" AvailableEquipment
Room --> "0..*" Slot

RoomType --> "1" RoomTypeCode
RoomType --> "1" RoomTypeDesignation
RoomType --> "0..1" RoomTypeDescription

Appointment -> "1" Room

OperationType --> "1" OperationTypeId
OperationType --> "1" OperationTypeStatus
OperationType --> "1" OperationTypeName
OperationType --> "1..*" RequiredStaff
RequiredStaff --> "1" Specialization
RequiredStaff --> "1" Function
RequiredStaff --> "1" NumberStaff
OperationType ---> "1" EstimatedDuration
OperationType ---> "3" Phase
Phase --> "1" PhaseDuration
Phase --> "1" PhaseDescription


OperationTypeRecord --> "1" OperationType
OperationTypeRecord --> "1" OperationTypeRecordId
OperationTypeRecord --> "1" OperationTypeRecordVersion
OperationTypeRecord --> "1" EffectiveDate
OperationTypeRecord --> "1" OperationTypeStatus
OperationTypeRecord --> "1" OperationTypeName
OperationTypeRecord --> "1..*" RequiredStaffRecord
OperationTypeRecord --> "1" EstimatedDuration
OperationTypeRecord --> "3" Phase
OperationTypeRecord --> "1" PhaseDuration
OperationTypeRecord --> "1" PhaseDescription
OperationTypeRecord --> "1" RequiredStaffRecord
RequiredStaffRecord --> "1" NumberStaff
RequiredStaffRecord --> "1" Function
RequiredStaffRecord --> "1" SpecializationDenomination



OperationRequest -> "1" OperationRequestId
OperationRequest --> "1" Priority
OperationRequest --> "1" Patient
OperationRequest --> "1" Doctor
OperationRequest ---> "1" OperationType
OperationRequest --> "1" DateOfRequest
OperationRequest --> "1" DeadlineDate
OperationRequest --> "1" OperationRequestStatus
OperationRequest --> "1" OperationRequestDescription

Appointment --> "1" OperationRequest
Appointment --> "1" Slot
Appointment --> "1" AppointmentId
Appointment --> "1" AppointmentStatus
'Appointment --> "1" AppointmentType
Appointment --> "1..*" Staff

Patient -> "1" Status
Patient -> "1" Name
Patient --> "1" DateBirth
Patient --> "1" Gender
Patient ---> "1" EmergencyContact
Patient --> "1" MRN
Patient -> "1" MedicalRecord
MedicalRecord --> "1" AppointmentHistory
Patient --> "0..*" AppointmentHistory
Patient --> "1" Email
Patient --> "1" Phone
Patient --> "1" Address
Patient---> "0..1" User
EmergencyContact --> "1" Phone

AppointmentHistory --> "1" AppointmentHistoryStatus
AppointmentHistory --> "1" AppointmentHistoryType
AppointmentHistory --> "1" CreatedAt


Staff --> "1" Status
Staff --> "1" Name
Staff --> "1" Function
Staff ---> "1" Email
Staff ---> "1" Phone
Staff --> "1" Address
Staff --> "1" LicenseNumber
Staff ---> "0..*" Slot
Staff --> "1" Specialization
Staff -> "1" User

Specialization --> "1" SpecializationDenomination
Specialization --> "1" SpecializationCode
Specialization --> "0..1" SpecializationDescription

Slot --> "1" Date
Slot --> "1" TimeInterval

MedicalRecord --> "0..*" MedicalCondition
MedicalRecord ---> "0..*" Allergy
MedicalRecord -> MedicalRecordDescription
Doctor ---> "0..*" MedicalRecord

Allergy --> "1" AllergyCode
Allergy --> "0..1" AllergyDescription
Allergy --> "1" AllergyDesignation

MedicalCondition --> "1" MedicalConditionCode
MedicalCondition --> "0..1" MedicalConditionDescription
MedicalCondition --> "1" MedicalConditionDesignation

@enduml
