@startuml
title "US 6.2.12 Process View (Level 3) | Visualization"

actor Admin
participant "<<Component>>\n Profile" as USER
participant "<<Service>>\n StaffService" as SERV

activate Admin
    Admin -> USER : get all active profiles
    activate USER 
        USER -> SERV : GetActiveStaffProfiles()
        activate SERV
            SERV ->o] : GET: api/Get-ActiveStaffProfiles()
            SERV <--o] : Ok(activeProfiles)
            SERV --> USER : activeProfiles
        deactivate SERV
        USER --> Admin : activeProfiles
    deactivate USER

    Admin -> USER : deactivate a profile
        activate USER
            USER -> SERV : DeactivateStaffProfile(id)
            activate SERV
                SERV ->o] : PUT: api/Deactivate-StaffProfile(id)
                SERV <--o] : Ok("Staff deactivated successfully.")
                SERV --> USER : success
            deactivate SERV
            USER --> Admin : success
        deactivate USER
deactivate Admin
@enduml