@startuml

title "US 6.2.6 - Process View [Level 2]"

autonumber

actor Admin as ADM
participant "Visualization" as VIS <<Container C4>>
participant "MDBackoffice" as SYS <<Container C4>>

activate ADM
ADM -> VIS : create patient profile
activate VIS

VIS -> SYS : CreatePatientProfile(json)
activate SYS

SYS --> VIS: success/insucess
deactivate SYS

VIS --> ADM : success/insucess
deactivate VIS
deactivate ADM

@enduml