@startuml
title "US 7.2.3 Process View (Level 3) | Visualization"

actor Doctor
participant "<<Component>>\n Get-Allergies" as USER
participant "<<Service>>\n StaffService" as SERV

activate Doctor
    Doctor -> USER : Asks to show list of allergies.
    activate USER
        USER -> SERV : GetAllAllergies(name)
        activate SERV
            SERV ->o] : GET: api/staff/get-allergies(name)
            SERV <--o] : Ok(allergies)
            SERV --> USER : allergies
        deactivate SERV
        USER --> Doctor : allergies
    deactivate USER
deactivate Doctor
@enduml