@startuml

title "US 5.1.12. - Process View [Level 2]"

autonumber

participant "<<component>>\n MDBackoffice" as bo

[o-> bo: createStaffProfile()
activate bo
<-- bo: success/insuccess
deactivate bo
@enduml