@startuml

title "US 5.1.8. - Process View [Level 2]"

autonumber

participant "<<component>>\n Backoffice" as bo
participant "<<component>>\n PublicAuthenticationAPI" as paa

[o-> bo: login()
activate bo

bo --> paa: 
activate paa
deactivate paa

<-- bo: success/insuccess
deactivate bo

@enduml