@startuml

title "US 5.1.7 - Process View [Level 3]"

autonumber
participant "UserRoute" as ROUTE <<route>>
participant "UserController" as CTRL <<controller>>
participant "UserService" as SVC <<service>>
participant "ExternalGoogleLoginAdapter" as IEL <<adapter>>
participant "HttpContext" as HC

[o-> ROUTE: GET /api/externallogin
activate ROUTE

ROUTE -> CTRL: externalLogin()
activate CTRL

CTRL ->  SVC: externalLogin()
activate SVC

SVC -> IEL : externalLogin()
activate IEL

IEL -> HC : challengeAsync(context, scheme, properties)
activate HC
deactivate HC
|||
deactivate IEL

deactivate SVC
deactivate CTRL
deactivate ROUTE

@enduml