@startuml

title "US 7.2.10 - Process View [Level 1]"

autonumber

actor Admin as ADM
participant "<<system (C4)>>\n Healthcare System" as SYS

activate ADM
ADM -> SYS : add new room type
activate SYS

SYS --> ADM : success/insucess
deactivate SYS
deactivate ADM

@enduml