@startuml
'https://plantuml.com/sequence-diagram

title "US 5.1.9. Process View (Level 2)"

autonumber

participant "<<component>>\n Visualization (UI)" as UI
participant "<<component>>\n Backoffice" as BACK


[o-> UI : asks to edit patient profile
activate UI

UI -> BACK : getPatientProfiles()
activate BACK

BACK --> UI : PatientProfilesList
deactivate BACK


<-- UI : shows list of patient profiles
deactivate UI


[o-> UI : selects an patient profile
activate UI

<-- UI : shows selected patient profile
deactivate UI


[o-> UI : edits patient profile editable fields
activate UI

UI -> BACK : editPatientProfile(json)
activate BACK

BACK --> UI : answer
deactivate BACK

<-- UI : answer
deactivate UI

@enduml