@startuml
title "US 7.2.17 Process View (Level 3) | Visualization"

actor Admin
participant "<<Component>>\n Create-Room" as USER
participant "<<Service>>\n RoomService" as SERV

activate Admin
    Admin -> USER : Asks to create a room.
    activate USER
        USER -> SERV : createRoom(id,\nmaintenanceSlots,\navailableEquipment,\ncapacity, type)
        activate SERV
            SERV ->o] : POST: api/Room/create(createRoom)
            SERV <--o] : Ok(room)
            SERV --> USER : room
        deactivate SERV
        USER --> Admin : room
    deactivate USER
deactivate Admin
@enduml