@startuml
'https://plantuml.com/sequence-diagram

title "US 5.1.N. Process View (Level 1)"

autonumber

actor Admin as ADM
participant "<<system (C4)>>\n Healthcare System" as SYS

ADM -> SYS : requests the list of the X profiles
activate SYS

SYS --> ADM : lists the X profiles
deactivate SYS
activate ADM

deactivate ADM

    opt search filters appliance

        ADM -> SYS : applies search filters (filter set F)
        deactivate ADM
        activate SYS

        SYS --> ADM : presents the search results
        deactivate SYS
        activate ADM
    end opt

ADM -> SYS : selects a profile
deactivate ADM
activate SYS

SYS --> ADM : shows profile
deactivate SYS
activate ADM

    alt edit profile
        ADM --> SYS : US 5.1.Y
        activate SYS
        deactivate SYS

    else deactivate profile

        ADM --> SYS : US 5.1.Z
        deactivate ADM
        activate SYS

    end alt

SYS --> ADM : confirmation of action
deactivate SYS

@enduml