@startuml

class User  <<entity>>{}
class Staff <<entity>>{}
class Patient  <<entity>>{}
class Doctor <<entity>>{}
class Appointment <<entity>>{}
class OperationRequest <<entity>>{}
class OperationType <<entity>> {}
class Room <<entity>>{}
class Specialization <<entity>> {}



User -> "1" Staff
User -> "0..1" Patient
Doctor -> "1" Staff
Staff -> "1" Specialization
OperationRequest --> "1" Doctor
Appointment -> "1" OperationRequest
OperationRequest -> "1" OperationType
Appointment -> "1" Room




@enduml
