@startuml

component User 
component Staff
component Patient 
component Doctor
component Appointment
component OperationRequest
component OperationType
component Room
component Specialization






@enduml
