@startuml
'https://plantuml.com/sequence-diagram

title "US 5.1.6. Process View (Level 3)"

autonumber

participant "<<component>>\n Routing" as ROUTE
participant "<<component>>\n BackOfficeUserController" as CONTROL

participant "<<component>>\n UserDTO" as UserDTO

participant "<<component>>\n AuthenticationService" as AUTHServ
participant "<<component>>\n UserRepository" as AUTHRepo


[o-> ROUTE : POST(json)
activate ROUTE

ROUTE -> CONTROL : loginStaff(json)
activate CONTROL

CONTROL -> UserDTO** : toDTO(credentialsData)

CONTROL -> AUTHServ : authenticateUser(noAuthUserDTO)
activate AUTHServ

AUTHServ -> AUTHRepo : findByID(emailString)
activate AUTHRepo


AUTHRepo --> AUTHServ : user
deactivate AUTHRepo

AUTHServ -> AUTHServ : hashPassword(passwordString)

AUTHServ -> AUTHServ : matchPassword(passwordStringHashed, password)

AUTHServ --> CONTROL : return
deactivate AUTHServ

CONTROL --> ROUTE : return
deactivate CONTROL

alt success
[o<-- ROUTE : 200 OK

else failure

[o<-- ROUTE : 400 Bad Request
deactivate ROUTE
end alt

@enduml