@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Unregistered \nBackoffice User" as USER
participant "System" as SYS

activate SYS
activate USER

SYS -> USER : Sends an email with a one-time setup link.

USER -> SYS : Sets their strong password\n to activate the account.

SYS --> USER : Sends an email to confirm the registration.

@enduml