@startuml
'https://plantuml.com/sequence-diagram

title "US 5.1.17. Process View (Level 3)"

autonumber

participant "<<route>>\n Routing" as ROUTE
participant "<<controller>>\n OperationRequisitionController" as CONTROL

participant "<<service>>\n StaffService" as STAFFServ
participant "<<repository>>\n StaffRepository" as STAFFRepo
participant "<<dto>>\n StaffDTO" as StaffDTO

participant "<<service>>\n AuthenticationService" as AUTHServ

participant "<<service>>\n OperationRequisitionService" as OPREQServ
participant "<<repository>>\n OperationRequisitionRepository" as OPREQRepo
participant "<<dto>>\n OperationRequisitionDTO" as OPREQDTO


[o-> ROUTE : GET() /api/operationrequisitions
activate ROUTE

ROUTE -> CONTROL : getOperationRequisitionsByDoctor()
activate CONTROL

CONTROL -> STAFFServ : findCurrentSessionDoctor()
activate STAFFServ

STAFFServ -> AUTHServ : getSessionUser()
activate AUTHServ

AUTHServ --> STAFFServ : user
deactivate AUTHServ

STAFFServ -> STAFFRepo : getDoctorByUser(user)
activate STAFFRepo

STAFFRepo --> STAFFServ : doctor
deactivate STAFFRepo

STAFFServ --> StaffDTO ** : toDTO(doctor)

STAFFServ --> CONTROL : doctorDTO
deactivate STAFFServ

CONTROL -> OPREQServ : getOperationRequisitionsByDoctor(doctorDTO)
activate OPREQServ

OPREQServ -> OPREQRepo : findAllByDoctor(doctorDTO)
activate OPREQRepo

OPREQRepo --> OPREQServ : operationRequisitionList
deactivate OPREQRepo

loop for all the elements in the list
OPREQServ -> OPREQDTO ** : toDTO(operationRequisition)

end loop

OPREQServ --> CONTROL : operationRequisitionDTOList
deactivate OPREQServ

CONTROL -> CONTROL : json(operationRequisitionDTOList)
activate CONTROL
deactivate CONTROL

CONTROL --> ROUTE : json
deactivate CONTROL

[o<- ROUTE : ok(json)
deactivate ROUTE

|||

[o-> ROUTE : POST(updatedData)
activate ROUTE

ROUTE -> CONTROL : updateOperationRequisition(updatedData)
activate CONTROL

CONTROL -> OPREQDTO ** : toDTO(updatedData)

CONTROL -> OPREQServ : updateOperationRequisition(operationRequisitionDTO)
activate OPREQServ

OPREQServ -> OPREQRepo : save(operationRequisitionDTO)
activate OPREQRepo

OPREQRepo --> OPREQServ : return
deactivate OPREQRepo

OPREQServ --> CONTROL : return
deactivate OPREQServ

CONTROL --> ROUTE : return
deactivate CONTROL


alt success
[o<-- ROUTE : 200 OK

else failure

[o<-- ROUTE : 400 Bad Request
deactivate ROUTE
end alt


@enduml