@startuml
'https://plantuml.com/sequence-diagram

title "US 5.1.17. Process View (Level 3)"

autonumber

participant "<<route>>\n Routing" as ROUTE
participant "<<controller>>\n OperationRequestsController" as CONTROL

participant "<<service>>\n StaffService" as STAFFServ
participant "<<repository>>\n StaffRepository" as STAFFRepo
participant "<<dto>>\n StaffDTO" as StaffDTO

participant "<<service>>\n UserService" as AUTHServ
participant "<<dto>>\n UserDto" as UserDto

participant "<<service>>\n OperationRequestsService" as OPREQServ
participant "<<domain>>\n OperationRequest" as OPRequest
participant "<<repository>>\n OperationRequestsRepository" as OPREQRepo
participant "<<dto>>\n OperationRequestsDTO" as OPREQDTO


[o-> ROUTE : GET() /api/OperationRequest
activate ROUTE

ROUTE -> CONTROL : getOperationRequestsByDoctor()
activate CONTROL

CONTROL -> STAFFServ : findCurrentSessionDoctor()
activate STAFFServ

STAFFServ -> AUTHServ : getSessionUser()
activate AUTHServ

AUTHServ -> UserDto ** : toDTO(user)

AUTHServ --> STAFFServ : userDto
deactivate AUTHServ

STAFFServ -> STAFFRepo : getDoctorByUser(userDto)
activate STAFFRepo

STAFFRepo --> STAFFServ : doctor
deactivate STAFFRepo

STAFFServ --> StaffDTO ** : toDTO(doctor)

STAFFServ --> CONTROL : doctorDTO
deactivate STAFFServ

CONTROL -> OPREQServ : getOperationRequestsByDoctor(doctorDTO)
activate OPREQServ

OPREQServ -> OPREQRepo : findAllByDoctor(doctorDTO)
activate OPREQRepo

OPREQRepo --> OPREQServ : operationRequestsList
deactivate OPREQRepo

loop for all the elements in the list
OPREQServ -> OPREQDTO ** : toDTO(operationRequests)

end loop

OPREQServ --> CONTROL : operationRequestsDTOList
deactivate OPREQServ

CONTROL -> CONTROL : json(operationRequestsDTOList)
activate CONTROL
deactivate CONTROL

CONTROL --> ROUTE : json
deactivate CONTROL

[o<- ROUTE : ok(json)
deactivate ROUTE

|||

[o-> ROUTE : PUT(json)
activate ROUTE

ROUTE -> CONTROL : Update(idString, updatedOperationRequestsDTO)
activate CONTROL


'//'GetByIdAsync

CONTROL -> OPREQServ : UpdateAsync(updatedOperationRequestsDTO)
activate OPREQServ

OPREQServ -> OPREQRepo : GetByIdAsync(dto.Id)
activate OPREQRepo

OPREQRepo --> OPREQServ : operationRequest
deactivate OPREQRepo

OPREQServ -> OperationRequest : ChangeDeadLineDate(dto.DeadLineDate)
OPREQServ -> OperationRequest : ChangePriority(dto.Priority)
OPREQServ -> OperationRequest : opRequest.ChangeDescription(dto.Description);
|||

OPREQServ -> OPREQRepo : save(operationRequest)
activate OPREQRepo

OPREQRepo --> OPREQServ : return
deactivate OPREQRepo

OPREQServ -> OPREQDTO ** : toDTO(operationRequest)

OPREQServ --> CONTROL : operationRequestDto
deactivate OPREQServ

CONTROL --> ROUTE : operationRequestDto
deactivate CONTROL


alt success
[o<-- ROUTE : 200 OK

else failure

[o<-- ROUTE : 400 Bad Request
deactivate ROUTE
end alt


@enduml