@startuml

title "US 7.2.13 - Process View [Level 2]"

autonumber

actor Admin as ADM
participant "Visualization" as VIS <<Container C4>>
participant "MDBackoffice" as SYS <<Container C4>>

activate ADM
ADM -> VIS : edit specialization
activate VIS


VIS -> SYS : EditSpecialization(json)
activate SYS

SYS --> VIS: success/insucess
deactivate SYS

VIS --> ADM : success/insucess
deactivate VIS
deactivate ADM

@enduml