@startuml
'https://plantuml.com/sequence-diagram

title "US 5.1.Y. Process View (Level 3)"

autonumber

participant "route:\nEditXRoute" as ROUTE
participant "controller:\nEditXController" as CTRL

participant "service:\nXService" as SER
participant "repository:\nXRepo" as REPO
participant "mapper:\nXMapper" as MAP
participant "dto:\nXDTO" as DTO

participant "persistence:\nPersistence" as PERSISTENCE

participant "service:\nEmailService" as EMAILServ
participant "service:\nTokenService" as TOKENServ
participant "token:\nToken" as TOKEN
participant "dto:\nTokenDTO" as TokenDTO
participant "repository:\nTokenRepository" as TOKENRepo


[o-> ROUTE : GET()
activate ROUTE

ROUTE -> CTRL : getXProfiles()
activate CTRL

CTRL -> SER : getXProfiles()
activate SER

SER -> REPO : findAll()
activate REPO

REPO --> SER : XProfilesList
deactivate REPO

loop for all the profiles in the list
SER -> MAP : toDTO(XProfile)
activate MAP

MAP -> DTO **

MAP --> SER : XProfileDTO
deactivate MAP
end loop

SER --> CTRL : XProfileDTOList
deactivate SER

CTRL --> ROUTE : XProfileDTOList
deactivate CTRL

<- ROUTE : XProfileDTOList
deactivate ROUTE

|||

[o-> ROUTE : PUT(json)
activate ROUTE

ROUTE -> CTRL : editXProfile(updatedData)
activate CTRL

CTRL -> DTO ** : toDTO(updatedData)

CTRL -> SER : editXProfile(XProfileDTO)
activate SER

SER -> REPO : save(XProfileDTO)
activate REPO

REPO -> PERSISTENCE : save(XProfileDTO)
activate PERSISTENCE
deactivate PERSISTENCE

REPO --> SER : answer
deactivate REPO

SER --> CTRL : answer
deactivate SER

opt when is changed contact information

CTRL -> EMAILServ : sendProfileEditEmail(userDTO)
activate EMAILServ

EMAILServ -> TOKENServ : generateProfileEditToken()
activate TOKENServ

TOKENServ -> TOKEN **

TOKENServ -> TOKENRepo : save(token)
activate TOKENRepo

TOKENRepo --> TOKENServ : return
deactivate TOKENRepo

TOKENServ -> TokenDTO ** : toDTO(token)

TOKENServ --> EMAILServ : tokenDTO
deactivate TOKENServ

EMAILServ -> EMAILServ : sendEmail(emailString, tokenDTO, emailTitle, emailBody)
activate EMAILServ

deactivate EMAILServ

EMAILServ --> CTRL :
deactivate EMAILServ
|||
end opt

CTRL --> ROUTE : answer
deactivate CTRL

<-- ROUTE : answer
deactivate ROUTE

@enduml