@startuml

title "US 6.2.20 - Process View [Level 1]"

autonumber

actor Admin as ADM
participant "<<system (C4)>>\n Healthcare System" as SYS

activate ADM
ADM -> SYS : remove operation type
activate SYS

SYS --> ADM : select operation type
deactivate SYS

ADM -> SYS: selects operastion type
activate SYS

SYS --> ADM : success/insuccess
deactivate SYS
deactivate ADM
@enduml