@startuml
'https://plantuml.com/sequence-diagram

title US 5.1.20 Process View (Level 3)

autonumber

participant "<<component>>\n Routing" as ROUTE
participant "<<component>>\n OperationTypeController" as CONTROL

participant "<<component>>\n StaffService" as STAFFServ
participant "<<component>>\n StaffRepository" as STAFFRepo
participant "<<component>>\n StaffDTO" as STAFFDTO

participant "<<component>>\n OperationTypeDTO" as OPTYDTO
participant "<<component>>\n OperationTypeService" as OPTYServ
participant "<<component>>\n OperationTypeRepository" as OPTYRepo
participant "<<component>>\n OperationType" as OPTY


[o-> ROUTE : GET()
activate ROUTE

ROUTE -> CONTROL : getAllStaff()
activate CONTROL

CONTROL -> STAFFServ : getAllStaffList()
activate STAFFServ

STAFFServ -> STAFFRepo : findAll()
activate STAFFRepo

STAFFRepo --> STAFFServ : staffList
deactivate STAFFRepo

loop for all staff in the staff list

STAFFServ -> STAFFDTO ** : toDTO(staff)
end loop

STAFFServ --> CONTROL : staffListDTO
deactivate STAFFServ

CONTROL -> CONTROL : json(staffListDTO)
activate CONTROL
deactivate CONTROL

CONTROL --> ROUTE : json
deactivate CONTROL

[o<-- ROUTE : ok(json)
deactivate ROUTE

|||

'probably json
[o-> ROUTE : POST(json)
activate ROUTE

ROUTE -> CONTROL : registerOperationType(json)
activate CONTROL

CONTROL -> OPTYDTO ** : toDTO(operationTypeData)

CONTROL -> OPTYServ : registerOperationType(operationTypeDTO)
activate OPTYServ

OPTYServ -> OPTYServ : checkIfOperationExists(operationTypeDTO)
activate OPTYServ

OPTYServ -> OPTYRepo : findByName(OperationTypeName)

activate OPTYRepo

OPTYRepo --> OPTYServ : return
deactivate OPTYRepo

OPTYServ --> OPTYServ : false
deactivate OPTYServ

|||

OPTYServ -> OPTY ** : OperationType(operationTypeDTO)

OPTYServ -> OPTYRepo : save(operationType)
activate OPTYRepo

OPTYRepo --> OPTYServ : return
deactivate OPTYRepo

OPTYServ --> CONTROL : return
deactivate OPTYServ

CONTROL --> ROUTE : return
deactivate CONTROL

alt success
[o<-- ROUTE : 200 OK

else failure

[o<-- ROUTE : 400 Bad Request
deactivate ROUTE
end alt


@enduml