@startuml

skinparam classAttributeIconSize 0
hide empty attributes
skinparam classBackgroundColor beige
skinparam ArrowColor #222222

package "<<aggregate>> User"{
    entity User  <<entity>>{}
}

package "<<aggregate>> Staff"{
    entity Staff <<entity>>{}
}
package "<<aggregate>> Patient"{
    entity Patient  <<entity>>{}
}
package "<<aggregate>> Doctor"{
    entity Doctor <<entity>>{}
}
package "<<aggregate>> Appointment"{
    entity Appointment <<entity>>{}
}
package "<<aggregate>> OperationRequest" {
    entity OperationRequest <<entity>>{}
}
package "<<aggregate>> OperationType"{
    entity OperationType <<entity>> {}
}

package "<<aggregate>> Room" {
    entity Room <<entity>>{}
}
package "<<aggregate>> Specialization" {
    entity Specialization <<entity>> {}
}


User -up--> "1" Staff 
User -up--> "0..1" Patient
Doctor ---> "1" Staff : is a
Staff ---> "1" Specialization
OperationRequest --> "1" Doctor : request by
Appointment ---> "1" OperationRequest : scheduling of
OperationRequest ---> "1" OperationType : defined by
Appointment ---> "1" Room : associated with




@enduml

