@startuml
'https://plantuml.com/sequence-diagram

title "US 5.1.5 - System Sequence Diagram"

autonumber

participant Patient as PAT
participant System as SYS

PAT -> SYS : requests the deletion of the account
activate PAT
activate SYS

SYS --> PAT : sends confirmation email to the patient's inbox

PAT -> SYS : confirms the decision to delete their account
deactivate PAT

SYS --> SYS : deletes identifiable data\n within the legal time frame

SYS -> SYS : registers account deletion\n on the system log

autonumber stop
SYS -[#white]> PAT

deactivate SYS

@enduml