@startuml
'https://plantuml.com/sequence-diagram

title "US 7.2.9 Process View (Level 1)"

autonumber

actor Doctor
participant "<<System (C4)>>\n Healthcare System" as SYS

activate Doctor
Doctor -> SYS : Wants to edit\nan Appointment.
activate SYS

SYS --> Doctor : Asks for the right variables.
deactivate SYS

Doctor -> SYS : Gives the right input.
activate SYS

SYS --> Doctor : Success message.
deactivate SYS

deactivate Doctor
deactivate SYS
@enduml