@startuml

title "US 6.2.5 - Process View [Level 2]"

autonumber

actor Patient as ADM
participant "Visualization" as VIS <<Container C4>>
participant "MDBackoffice" as SYS <<Container C4>>

activate ADM
ADM -> VIS : initiates login
activate VIS

VIS -> SYS : LoginExternal()
activate SYS

SYS --> VIS: success/insucess
deactivate SYS

VIS --> ADM : grants access to features
deactivate VIS
deactivate ADM

@enduml