@startuml

title "US 5.1.4. - Process View [Level 2]"

autonumber

participant "<<component>>\n MDBackoffice" as bo

[o-> bo: updatePatientInformation()
activate bo
<-- bo: success/insuccess
deactivate bo

@enduml